# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/at7.xdc

# XDC: /home/nks/Desktop/at7_ex16_bd_adc/project_1/project_1.srcs/constrs_1/new/ads7056_P4.xdc

# XDC: new/ads7056_8adc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sys_ctrl_0_0/design_1_sys_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sys_ctrl_0_0 || ORIG_REF_NAME==design_1_sys_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_controller_0_0/design_1_led_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_controller_0_0 || ORIG_REF_NAME==design_1_led_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_read_controller_0_0/design_1_fifo_read_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_read_controller_0_0 || ORIG_REF_NAME==design_1_fifo_read_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_0/design_1_SPI_ADC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_0 || ORIG_REF_NAME==design_1_SPI_ADC_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_1_0/design_1_SPI_ADC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_1_0 || ORIG_REF_NAME==design_1_SPI_ADC_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC2FIFO_0_0/design_1_ADC2FIFO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADC2FIFO_0_0 || ORIG_REF_NAME==design_1_ADC2FIFO_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_3/design_1_SPI_ADC_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_3 || ORIG_REF_NAME==design_1_SPI_ADC_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_4/design_1_SPI_ADC_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_4 || ORIG_REF_NAME==design_1_SPI_ADC_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_5/design_1_SPI_ADC_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_5 || ORIG_REF_NAME==design_1_SPI_ADC_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_6/design_1_SPI_ADC_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_6 || ORIG_REF_NAME==design_1_SPI_ADC_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_7/design_1_SPI_ADC_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_7 || ORIG_REF_NAME==design_1_SPI_ADC_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_ADC_0_8/design_1_SPI_ADC_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_ADC_0_8 || ORIG_REF_NAME==design_1_SPI_ADC_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC2FIFO_0_1/design_1_ADC2FIFO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADC2FIFO_0_1 || ORIG_REF_NAME==design_1_ADC2FIFO_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC2FIFO_0_2/design_1_ADC2FIFO_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADC2FIFO_0_2 || ORIG_REF_NAME==design_1_ADC2FIFO_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC2FIFO_0_3/design_1_ADC2FIFO_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADC2FIFO_0_3 || ORIG_REF_NAME==design_1_ADC2FIFO_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIFO_RD_Mux_0_1/design_1_FIFO_RD_Mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FIFO_RD_Mux_0_1 || ORIG_REF_NAME==design_1_FIFO_RD_Mux_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
